name: Build and Push Docker Image

on:
  push:
    branches:
      - feat/github-action

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: githubaction

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd back
          docker build -t ${{ secrets.USERNAME }}/my-backend:latest \
                       -t ${{ secrets.USERNAME }}/my-backend:${{ steps.vars.outputs.sha_short }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.USERNAME }}/my-backend:latest
          docker push ${{ secrets.USERNAME }}/my-backend:${{ steps.vars.outputs.sha_short }}

      - name: Display pushed tags
        run: |
          echo "Images pushed:"
          echo "- ${{ secrets.USERNAME }}/my-backend:latest"
          echo "- ${{ secrets.USERNAME }}/my-backend:${{ steps.vars.outputs.sha_short }}"
