name: Build and Push Docker Images

on:
  push:
    branches:
      - feat/github-action

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: githubaction
    strategy:
      matrix:
        service: [back, front]
        include:
          - service: back
            image_name: my-backend
          - service: front
            image_name: my-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ secrets.USERNAME }}/${{ matrix.image_name }}:latest \
                       -t ${{ secrets.USERNAME }}/${{ matrix.image_name }}:${{ steps.vars.outputs.sha_short }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.USERNAME }}/${{ matrix.image_name }}:latest
          docker push ${{ secrets.USERNAME }}/${{ matrix.image_name }}:${{ steps.vars.outputs.sha_short }}

      - name: Display pushed tags
        run: |
          echo "✅ ${{ matrix.service }} images pushed:"
          echo "- ${{ secrets.USERNAME }}/${{ matrix.image_name }}:latest"
          echo "- ${{ secrets.USERNAME }}/${{ matrix.image_name }}:${{ steps.vars.outputs.sha_short }}"
