name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: githubaction
    strategy:
      matrix:
        service: [back, front, worker]
        include:
          - service: back
            build_path: back
            image_name: my-backend
            dockerfile: Dockerfile
          - service: front
            build_path: front
            image_name: my-frontend
            dockerfile: Dockerfile
          - service: worker
            image_name: my-worker
            build_path: back
            dockerfile: Dockerfile.worker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and tag Docker image
        run: |
          cd ${{ matrix.build_path }}
          docker build -f ${{ matrix.dockerfile }} -t ${{ secrets.USERNAME }}/${{ matrix.image_name }}:latest \
                       -t ${{ secrets.USERNAME }}/${{ matrix.image_name }}:${{ steps.vars.outputs.sha_short }} .

      - name: Push Docker images
        run: |
          docker push ${{ secrets.USERNAME }}/${{ matrix.image_name }}:latest
          docker push ${{ secrets.USERNAME }}/${{ matrix.image_name }}:${{ steps.vars.outputs.sha_short }}

      - name: Trigger Render deploy via API
        env:
          RENDER_SERVICE_ID_BACKEND: srv-d1a0p495pdvs73aaslr0
          RENDER_SERVICE_ID_WORKER: srv-d1bdje2dbo4c73cdv69g
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
        run: |
          echo "Triggering backend deploy..."
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID_BACKEND}/deploys" \
              -H "Authorization: Bearer ${RENDER_API_TOKEN}" \
              -H "Accept: application/json"
          echo "Triggering worker deploy..."
          curl -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID_WORKER}/deploys" \
              -H "Authorization: Bearer ${RENDER_API_TOKEN}" \
              -H "Accept: application/json"
